language: python
dist: trusty
sudo: required
branches:
  only:
    - develop
    - master
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
install:
  # Install TA-Lib
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xzvf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..

  # Install bcolz
  - pip install Cython
  - pip install bcolz
  - pip install -r requirements.txt

  # Install Test Deps
  - pip install TA-Lib
  - pip install coverage
  - pip install -U setuptools
  - pip install .
script:
  - rqalpha update_bundle
  - python test.py
  - python test.py module
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.rqalpha
