# 白名单，设置可以直接在策略代码中指定哪些模块的配置项目
whitelist: [base, extra, validator, mod]

base:
  # 可以指定回测的唯一ID，用户区分多次回测的结果
  run_id: 9999
  # 数据源所存储的文件路径
  data_bundle_path: ~
  # 启动的策略文件路径
  strategy_file: strategy.py
  # 设置支持的证券，目前支持 `stock` (股票策略)、`future` (期货策略)及 `stock_future` (混合策略)
  securities: stock
    # 运行类型，`b` - back_test 为回测，`p` paper_trading 为模拟交易, `r` realtime 为实盘交易。
  run_type: b

back_test:
  # 回测起始日期
  start_date: 2016-06-01
  # 回测结束日期(如果是实盘，则忽略该配置)
  end_date: 2050-01-01
  # 股票起始资金，默认为0
  stock_starting_cash: 0
  # 期货起始资金，默认为0
  future_starting_cash: 0

